//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Guide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Book_Id { get; set; }
        public string Book_Name { get; set; }
        public string Book_Email { get; set; }
        public string Book_Phone { get; set; }
        public Nullable<int> Book_Cildren { get; set; }
        public Nullable<int> Book_Adults { get; set; }
        public string BookeddFor { get; set; }
    }
}
