//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Guide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cust_FeedBack
    {
        public int CusFeed_Id { get; set; }
        public string CusFeed_Name { get; set; }
        public string CusFeed_Phone { get; set; }
        public string CusFeed_Email { get; set; }
        public string CusFeed_Message { get; set; }
    }
}
