//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Guide.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KarnelTravelDatabaseEntities : DbContext
    {
        public KarnelTravelDatabaseEntities()
            : base("name=KarnelTravelDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Cust_FeedBack> Cust_FeedBack { get; set; }
        public virtual DbSet<Cust_Subs> Cust_Subs { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Resort> Resorts { get; set; }
        public virtual DbSet<Rest_Cat> Rest_Cat { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<TouristSpot> TouristSpots { get; set; }
        public virtual DbSet<Travel> Travels { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Registration> User_Registration { get; set; }
    }
}
