//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Guide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resort
    {
        public int Resort_Id { get; set; }
        public string Resort_Name { get; set; }
        public string Resort_PriceRange { get; set; }
        public string Resort_Membership { get; set; }
        public string Resort_Facilities { get; set; }
        public string Resort_Image { get; set; }
        public string Resort_Image2 { get; set; }
        public string Resort_Image3 { get; set; }
        public int Resort_City { get; set; }
    
        public virtual City City { get; set; }
    }
}
