//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Guide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int Restaurant_Id { get; set; }
        public string Restaurant_Name { get; set; }
        public string Restaurant_PriceRange { get; set; }
        public string Restaurant_Rating { get; set; }
        public string Restaurant_Image { get; set; }
        public string Restaurant_Image2 { get; set; }
        public string Restaurant_Image3 { get; set; }
        public string Restaurant_Discription { get; set; }
        public int Restaurant_City { get; set; }
        public int Restaurant_Catagories { get; set; }
    
        public virtual City City { get; set; }
        public virtual Rest_Cat Rest_Cat { get; set; }
    }
}
