//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Guide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public int Tavel_Id { get; set; }
        public string Travel_vehicles { get; set; }
        public string Travel_Type { get; set; }
        public string Travel_Capacity { get; set; }
        public string Travel_Rent { get; set; }
        public string Travel_Image { get; set; }
        public string Travel_Image2 { get; set; }
    }
}
